apiVersion: apps/v1
kind: Deployment
metadata:
  name:  challenge3
  namespace: default
  labels:
    app:  challenge3
spec:
  selector:
    matchLabels:
      app: challenge3
  replicas: 2
  template:
    metadata:
      labels:
        app:  challenge3
    spec:
      containers:
      - name:  challenge3
        image:  nginx:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort:  80
          name:  challenge3
      restartPolicy: Always
