apiVersion: v1
kind: Service
metadata:
  name: challenge3-srv
  namespace: default
spec:
  selector:
    app: challenge3
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: challenge3
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31234
