apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello
        spec:
        containers:
        - name: hello
        image: registry.digitalocean.com/ara-cr/pt-client
        imagePullSecrets:
        - name: digocian
 
 

