apiVersion: v1
kind: Pod
metadata:
  name: "pt-client"
  labels:
    app: "pt-client-lbl"
spec:
  replicas: 3
  containers:
  - name: pt-client
    image: "registry.digitalocean.com/ara-cr/pt-client:latest"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    ports:
    - containerPort:  80
      name:  http
  restartPolicy: Always