apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
  labels:
    name: storage-pod

spec:
  containers:
  - name: storage-pod
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - name: myvolume
        mountPath: /etc/certs
  volumes:
    - name: myvolume
      emptyDir: {}

