apiVersion: v1
kind: Service
metadata:
  name: nginx-np
  namespace: default
spec:
  selector:
    app: ptc-lbl
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31111 
