apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: ptc-lbl
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080 
