apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      server: apache
  template:
    metadata:
      labels:
        server: apache
    spec:
      containers:
      - name: apache-wevserver
        image: httpd:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        # command: ["/bin/bash", "-c"]
        # args:
        # - sleep 300
