apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs-name
  labels:
    app: nginx-rs-lbl
spec:
  replicas: 5 
  selector:
    matchLabels:
      myapp: nginx-new
  template:
    metadata:
      labels:
        myapp: nginx-new
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: web
          containerPort:  80
          protocol: TCP
        env:
        - name: NGX_VERSION
          value: 1.16.1
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
