apiVersion: v1
kind: PersistentVolume
metadata:
  name: challenge-pv
spec:
  storageClassName: challenge4
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/challenge4

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: challenge-pvc
  namespace: default
  labels:
    app: challenge-pvc
spec:
  storageClassName: challenge4
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: "nginxdemo"
  namespace: default
  labels:
    app: "nginxdemo"
spec:
  containers:
  - name: nginxdemo
    image: nginx:latest
    resources:
      limits:
        cpu: 200m 
        memory: 500Mi
    ports:
    - containerPort:  80
    volumeMounts:
    - name: localpvc
      mountPath: /var/www/html
  volumes:
    - name: localpvc
      persistentVolumeClaim:
        claimName : challenge-pvc
      



